from django.conf.urls.defaults import patterns, url, include
import semantic_store.views
from semantic_store.rdfviews import ProjectView

urlpatterns = patterns('',
    url(r'^manifests(?:/(?P<uri>.+))?/?$', 
        semantic_store.views.manifest, 
        name="semantic_store_manifest"),
    url(r'^repositories(?:/(?P<uri>.+))?/?$', 
        semantic_store.views.repositories, 
        name="semantic_store_repositories"),
    url(r'^repositories/(?P<uri>.+)/annotations/?$', 
        semantic_store.views.repositories, 
        name="semantic_store_repositories"),
    url(r'^projects(?:/(?P<identifier>.+))?/?$', 
        ProjectView.as_view(), 
        name="semantic_store_projects"),
    url(r'^projects/(?P<identifier>.+)/annotations(?:/(?P<anno_identifier>.+))?/?$', 
        semantic_store.views.project_annotations, 
        name="semantic_store_project_annotations"),
    url(r'^manuscripts(?:/(?P<uri>.+))?/?$', 
        semantic_store.views.manuscripts, 
        name="semantic_store_manuscripts"),
    url(r'^manuscripts/(?P<uri>.+)/annotations/?$', 
        semantic_store.views.manuscript_annotations, 
        name="semantic_store_manuscripts"),
    url(r'^manuscript_collections(?:/(?P<uri>.+))/?$', 
        semantic_store.views.manuscript_collections, 
        name="semantic_store_manuscript_collections"),
    url(r'^manuscript_collections/(?P<uri>.+)/annotations/?$', 
        semantic_store.views.manuscript_collection_annotations, 
        name="semantic_store_project"),
    url(r'^collections(?:/(?P<uri>.+))/?$', 
        semantic_store.views.collections, 
        name="semantic_store_collections"),
    url(r'^collections/(?P<uri>.+)/annotations/?$', 
        semantic_store.views.collection_annotations, 
        name="semantic_store_project"),
    url(r'^users(?:/(?P<username>.+))?/?$', 
        semantic_store.views.users, 
        name="semantic_store_user"),
    url(r'^users/(?P<username>.+)/annotations/?$', 
        semantic_store.views.user_annotations, 
        name="semantic_store_user_annotations"),
    url(r'^annotations(?:/(?P<anno_uri>.+))?/?$', 
        semantic_store.views.annotations, 
        name="semantic_store_annotations"),
)
