#! /usr/bin/env python
# -*- mode: python -*-

import sys

from os import chdir, unlink
from os.path import dirname, isdir, join, realpath

from subprocess import call

from logging import basicConfig, info, INFO

banner = (79 * '-')
basicConfig(
    format="\n".join([banner, '%(asctime)s - %(message)s', banner]),
    level=INFO,
    stream=sys.stdout
)

base_dir = dirname(dirname(realpath(__file__)))
js_dir = join(base_dir, "src", "main", "resources", "static", "js")

def closure_build(dest, cmd):
    print repr(cmd)
    with file(join(js_dir, dest), "w") as dest_file:
        call(
            ["python"] + cmd,
            cwd=js_dir,
            stdout=dest_file
        )

chdir(base_dir)

info("JS Dependencies (yarn)")
call(["yarn"])

info("Google Closure Dependencies")
closure_build("atb-deps.js", [
    "closure-library/closure/bin/build/depswriter.py",
    "--root_with_prefix=atb ../../../atb/",
    "--root_with_prefix=jquery ../../../jquery",
    "--root_with_prefix=sc ../../../sc",
    "--root_with_prefix=fabric ../../../fabric",
    "--root_with_prefix=n3 ../../../n3"
])

info("Google Closure Compiler")
closure_build("all-js-code.js", [
    "closure-library/closure/bin/build/closurebuilder.py",
    "--root=.",
    "--input=dm/fluid_workspace.js",
    "--output_mode=compiled",
    "--compiler_jar=compiler.jar",
    "--compiler_flags=--language_in=ECMASCRIPT5"
])

info("JS Frontend Build (Webpack)")
call(["npm", "run", "build"])
unlink(join(js_dir, "dm-styles.js"))

info("Java Backend Build (Maven)")
call(["mvn", "clean", "package"])
