#! /usr/bin/env python
# -*- mode: python -*-

import sys

from os import chdir, execvp
from os.path import dirname, isfile, join, realpath

base_dir = dirname(dirname(realpath(__file__)))

local_conf = join(base_dir, "local.conf")
conf_param = isfile(local_conf) and ["-Dconfig.file=" + local_conf] or []

cmd = ["java"] +\
      conf_param +\
      ["-jar", join(base_dir, "target", "dm-1.0-SNAPSHOT.jar")] +\
      sys.argv[1:]

chdir(base_dir)
execvp(cmd[0], cmd)
